apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: ci-pipeline-run-
  labels:
    app: ci-pipeline
spec:
  pipelineRef:
    name: ci-pipeline
  params:
    - name: git-url
      value: "https://github.com/oladapooloyede/dotnet-pg-microservice"
    - name: git-revision
      value: master
    - name: image-name
      value: "image-registry.openshift-image-registry.svc:5000/sandbox/dotnet-pg-microservice:latest"
    - name: kustomize-repo-url
      value: "https://github.com/oladapooloyede/dotnet-cicd"
    - name: namespace
      value: "sandbox"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
