apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: dotnet-pg-microservice
    newName: image-registry.openshift-image-registry.svc:5000/sandbox/dotnet-pg-microservice
    digest: sha256:3cd753e505ac09288b4f22a3e98b96afe3be97f89d1e8bf446522dd2825213f3
