apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: dotnet-pg-microservice
    newName: image-registry.openshift-image-registry.svc:5000/sandbox/dotnet-pg-microservice:latest
    digest: sha256:b54b190a9a6b5c00f369b4350a8c255f78f1dcc580a2be8f0e106ddfbed66d47
