apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: dotnet-pg-microservice
    newName: image-registry.openshift-image-registry.svc:5000/sandbox/dotnet-pg-microservice:latest
    digest: sha256:590708d2a0115a7c41e1dd074947b5125044c74a1bd9c046e88836d1e598d0c0
